
---

- hosts: webserver
  become: true
  tasks: 
  - name: first task
    ping: 

  - name: creating user
    user: name=aanandsri uid=1007

- hosts: ansible3
  become: true
  tasks:
  - file: path=/root/demo state=directory
