
---

- hosts: webserver
  become: true
  tasks:
   - name: logic test
     apt: name=apache2 state=remove
     when: ansible_hostname != 'ansible2'

   - name: Install Apache2
     apt: name=apache2 state=present

   - name: Start Apache2
     service: name=apache2 enabled=yes state=started

   - name: Displaying myName
     shell: echo Hello world > /var/www/html/index.html


